# ============================================
# SANCHALA OS - qBittorrent Preferences
# ============================================

[Preferences]
Advanced\AnonymousMode=true
Advanced\DisableRecursiveDownload=false
Advanced\IncludeOverhead=false
Bittorrent\DHT=true
Bittorrent\Encryption=1
Bittorrent\LSD=true
Bittorrent\MaxRatio=2
Bittorrent\MaxRatioAction=0
Bittorrent\PeX=true
Bittorrent\uTP=true
Connection\GlobalDLLimit=0
Connection\GlobalDLLimitAlt=1024
Connection\GlobalUPLimit=0
Connection\GlobalUPLimitAlt=512
Connection\PortRangeMin=6881
Connection\ResolvePeerCountries=true
Connection\UPnP=true
Downloads\DiskWriteCacheSize=256
Downloads\DiskWriteCacheTTL=60
Downloads\PreAllocation=true
Downloads\SavePath=/home/@USER@/Downloads/Torrents
Downloads\StartInPause=false
Downloads\TempPath=/home/@USER@/Downloads/Torrents/Incomplete
Downloads\TempPathEnabled=true
Downloads\UseIncompleteExtension=true
General\AlternatingRowColors=true
General\CloseToTray=true
General\ExitConfirm=true
General\Locale=
General\NoSplashScreen=true
General\PreventFromSuspendWhenDownloading=true
General\SystrayEnabled=true
Queueing\IgnoreSlowTorrents=true
Queueing\MaxActiveDownloads=5
Queueing\MaxActiveTorrents=10
Queueing\MaxActiveUploads=5
Queueing\QueueingEnabled=true
Scheduler\days=EveryDay
Search\SearchEnabled=true
WebUI\Address=127.0.0.1
WebUI\CSRFProtection=true
WebUI\ClickjackingProtection=true
WebUI\Enabled=false
WebUI\LocalHostAuth=true
WebUI\Port=8080
WebUI\SecureCookie=true
