# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Sanchala OS Installer - Bootloader Module

---
efiBootLoader: "grub"

kernel: "/vmlinuz-linux-hardened"
img: "/initramfs-linux-hardened.img"
fallback: "/initramfs-linux-hardened-fallback.img"

timeout: 10

grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"

efiDirectory: "/boot/efi"

installEFIFallback: true
