# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Sanchala OS Installer - Services Module

---
services:
    - name: "NetworkManager"
      mandatory: true
    - name: "sddm"
      mandatory: true
    - name: "apparmor"
      mandatory: false
    - name: "firewalld"
      mandatory: false
    - name: "bluetooth"
      mandatory: false
    - name: "fstrim.timer"
      mandatory: false
    - name: "cups"
      mandatory: false

targets:
    - name: "graphical"
      mandatory: true
