# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Sanchala OS Installer - Unpackfs Module

---
unpack:
    - source: "/run/archiso/bootmnt/sanchala/x86_64/airootfs.sfs"
      sourcefs: "squashfs"
      destination: ""
