# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Sanchala OS Installer - Welcome Module

showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: true
showDonateUrl: false

requirements:
    requiredStorage: 30
    requiredRam: 4.0
    internetCheckUrl: https://sanchala.id
    check:
        - storage
        - ram
        - power
        - internet
        - root
        - screen
    required:
        - storage
        - ram
        - root

geoip:
    style: "none"
