[General]
background=/usr/share/sanchala/wallpapers/default-dark.png
blur=true
blurRadius=40
primaryColor=#3949AB
accentColor=#536DFE
darkMode=true
showUserAvatar=true
showSessionSelector=true
showVirtualKeyboard=true
clockFormat=HH:mm
dateFormat=dddd, MMMM d
font=Inter
fontSize=14
