[General]
format=png
quality=95
delay=0
cursor=false
decorations=true

[Behavior]
clipboard=true
save=true
sound=true
notify=true

[Paths]
save_dir=$HOME/Pictures/Screenshots
filename_template=Screenshot_%Y-%m-%d_%H-%M-%S
