# SPDX-License-Identifier: GPL-3.0
# Sanchala OS - Snapper Configuration
# /etc/snapper/snapper.conf

# Directory for configurations
SNAPPER_CONFIGS="root home"

# Additional cleanup algorithms to run
# (timeline, empty-pre-post, number)
SNAPPER_CLEANUP_ALGORITHMS="timeline number empty-pre-post"

# Enable snapper systemd timers by default
# - snapper-timeline.timer: Creates timeline snapshots
# - snapper-cleanup.timer: Cleans old snapshots
# - snapper-boot.timer: Creates boot snapshot
SNAPPER_SYSTEMD_TIMERS="yes"
