title   Sanchala OS (Safe Mode)
linux   /sanchala/boot/x86_64/vmlinuz-linux-hardened
initrd  /sanchala/boot/x86_64/initramfs-linux-hardened.img
options archisobasedir=sanchala archisolabel=SANCHALA_202608 nomodeset
