.TH SANCHALA-WIDGETS-MANAGER 1 "2024" "Sanchala OS" "User Commands"
.SH NAME
sanchala-widgets-manager \- Desktop widget management
.SH SYNOPSIS
.B sanchala-widgets-manager
[\fIcommand\fR] [\fIoptions\fR]
.SH DESCRIPTION
Add, remove, and configure desktop widgets (Plasma plasmoids).
.SH COMMANDS
.TP
.B list
List installed widgets
.TP
.B add \fIwidget\fR
Add widget to desktop
.TP
.B remove \fIwidget\fR
Remove widget from desktop
.TP
.B search \fIquery\fR
Search available widgets
.TP
.B install \fIpackage\fR
Install new widget package
.SH EXAMPLES
.TP
sanchala-widgets-manager list
.TP
sanchala-widgets-manager add org.kde.plasma.weather
.SH AUTHOR
Sanchala OS Team
