.TH SANCHALA-SHORTCUTS-HELP 1 "2024" "Sanchala OS" "User Commands"
.SH NAME
sanchala-shortcuts-help \- Keyboard shortcuts reference and customization
.SH SYNOPSIS
.B sanchala-shortcuts-help
[\fIcommand\fR] [\fIoptions\fR]
.SH DESCRIPTION
View and customize keyboard shortcuts for the desktop environment.
.SH COMMANDS
.TP
.B show
Display all keyboard shortcuts
.TP
.B search \fIquery\fR
Search shortcuts by action name
.TP
.B category \fIname\fR
Show shortcuts in category (window, workspace, system, app)
.TP
.B set \fIaction\fR \fIkeys\fR
Set custom shortcut
.SH EXAMPLES
.TP
sanchala-shortcuts-help show
.TP
sanchala-shortcuts-help category window
.SH AUTHOR
Sanchala OS Team
