# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Sanchala OS Calamares Installer Configuration
# https://sanchala.id

---
modules-search: [ local, /usr/lib/calamares/modules ]

instances:
- id:       sanchalalocale
  module:   locale
  config:   locale.conf
  
- id:       sanchalakeyboard
  module:   keyboard
  config:   keyboard.conf

- id:       sanchalausers
  module:   users
  config:   users.conf

sequence:
- show:
  - welcome
  - locale@sanchalalocale
  - keyboard@sanchalakeyboard
  - partition
  - users@sanchalausers
  - summary

- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale@sanchalalocale
  - keyboard@sanchalakeyboard
  - localecfg
  - luksbootkeyfile
  - users@sanchalausers
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - bootloader
  - packages
  - shellprocess
  - umount

- show:
  - finished

branding: sanchala

prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true

debug: false
